### ISSUE TITLE
OK - finished web site so what after

### ISSUE THREAD

**Issue by eliassal** [sitepoint-editors/note-board-email-course#1]
Hi James, thanks first of all, I read the book on sitepoint and should say that it is very useful and well organized except the fact that you end the book without any instructions on how to use the web site (update, delete......) and how to persist data to a production sqllite.
Also, at the end of Chapter 7, you recommend a test of 3 urls, buet between this step and end of ch 9, a lot of code and pages introduced with testing step by step. When I finished CH 9 and did node server.js I started getting errors and as I am new and learning node and JS as well as sqllite  at the same time it was difficult to me to figure out. I finished by deleting my web site and cloned yours from this site which I should say it works like a charm

**Comment by jameshibbard** [comment]
Hi, 
Glad to hear you found the book useful and thanks for the feedback.
The errors will probably be because this is the old repo. 
The new(er) version can be found here: https://github.com/sitepoint-editors/notes-board
If you need any help with any SitePoint code, you can always ask in our forums: https://www.sitepoint.com/community/

**Comment by eliassal** [comment]
Thanks for the quick response. After years, My subscription to sitepoint expired 1 month back, I am not sure I can join the community.
Anyway, I went through very quickly on couple of pages in the new version, they are a little bit different than the book. One question if you allow, how can I debug this application? I googled a little bit I understood that from node docs that there is a possibility to use an argument "inspect" but they are not clear on how to use it. Also, when I tried it I was getting 

> Timeout (2000) waiting for 127.0.0.1:9229 to be free

in spite of the fact no other node app is running. Any idea? What do you use for debugging?
Thanks again

**Comment by jameshibbard** [comment]
Here's how you can use inspect.
https://www.sitepoint.com/debug-node-app-tips-tricks-tools/#nodejsv8inspector

**Comment by eliassal** [comment]
So many thanks, it is working like a charm
